# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZESTgsI0DiDH9KTgYL-BCEIDSK8Zmeg
"""

!pip install -q streamlit

import streamlit as st
import numpy as np
import joblib

# Load trained model
model = joblib.load("rf_model.pkl")

st.set_page_config(page_title="USD/MYR Exchange Rate Predictor", layout="centered")
st.title("📈 USD/MYR Exchange Rate Predictor")

st.markdown("Enter macroeconomic indicators to predict **log(USD/MYR)** exchange rate.")

# Sidebar input
st.sidebar.header("Input Macroeconomic Indicators")
features = {
    'MSIA_IR_lag1': st.sidebar.number_input("🇲🇾 Malaysia Interest Rate", value=3.0),
    'MSIA_UR_lag1': st.sidebar.number_input("🇲🇾 Malaysia Unemployment Rate", value=3.5),
    'FBMKLCI_Index_lag1': st.sidebar.number_input("🇲🇾 FBMKLCI Index", value=1450.0),
    'VIX_lag1': st.sidebar.number_input("🌎 VIX Index", value=18.0),
    'GVZ_lag1': st.sidebar.number_input("🌎 GVZ Index", value=19.0),
    'USA_IR_lag1': st.sidebar.number_input("🇺🇸 US Interest Rate", value=5.25),
    'USA_IPI_lag1': st.sidebar.number_input("🇺🇸 US Industrial Production Index", value=105.0),
    'USA_UR_lag1': st.sidebar.number_input("🇺🇸 US Unemployment Rate", value=3.6),
    'USA_M1_lag1': st.sidebar.number_input("🇺🇸 US M1 Money Supply", value=18000.0),
    'USA_CPI.1_lag1': st.sidebar.number_input("🇺🇸 US CPI", value=305.0),
    'S&P_Index_lag1': st.sidebar.number_input("🇺🇸 S&P 500 Index", value=4400.0),
    'MSIA_NetTrade_lag1': st.sidebar.number_input("🇲🇾 Malaysia Net Trade", value=25.0)
}

input_array = np.array([list(features.values())])

if st.button("🚀 Predict log(USD/MYR)"):
    prediction = model.predict(input_array)[0]
    st.subheader("📊 Prediction Result")
    st.write(f"### 🔹 Predicted `log(USD/MYR)` = `{prediction:.4f}`")